### Add image for Article

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data;boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="media.jpg"
Content-Type: image/jpeg

< Man.jpg
--WebBoundary--

> {%
client.global.set('mediaName',response.body.name);
 %}

### Add multiple images for Article

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data;boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="media.jpg"
Content-Type: image/jpeg

< Man.jpg

--WebBoundary
Content-Disposition: form-data; name="files"; filename="media.png"
Content-Type: image/png

< Enzymes.png

--WebBoundary
Content-Disposition: form-data; name="files"; filename="media.jpg"
Content-Type: image/jpeg

< Prebiotics.jpg
--WebBoundary--

### Get all Articles

GET http://localhost:8080/articles/getAll

### Get Article by id

GET http://localhost:8080/articles/getById?id=1

### Get Article by non-existent id

GET http://localhost:8080/articles/getById?id=999

### Create Article without image

POST http://localhost:8080/articles/save
Content-Type: application/json

{
  "id": 0,
  "name": "What’s in Your Multivitamin? Here Are 10 Ingredients To Look Out For",
  "category": "wellness",
  "text": "There is no question that the entire human body functions best when it has a steady supply of high-quality nutrition. A deficiency of any nutrient has profound effects on the human system because the body is a complex system dependent upon the proper functioning of many interdependent systems. ",
  "firstItemId": 4,
  "secondItemId": 8,
  "thirdItemId": 3
}

### Create Article with image

POST http://localhost:8080/articles/save
Content-Type: application/json

{
  "id": 0,
  "name": "5 Ways Vegetarians Can Get More Protein In Their Diet",
  "category": "nutrition",
  "text": "There is no question that the entire human body functions best when it has a steady supply of high-quality nutrition. A deficiency of any nutrient has profound effects on the human system because the body is a complex system dependent upon the proper functioning of many interdependent systems. ",
  "firstItemId": 2,
  "secondItemId": 11,
  "thirdItemId": 10,
  "image": "{{mediaName}}"
}

### Remove Article by id

POST http://localhost:8080/articles/removeById/5

### Restore Article by id

POST http://localhost:8080/articles/restoreById/5


