### Add image for Vitamin

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data;boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="media.jpg"
Content-Type: image/jpeg

< VitaminD.jpg

> {%
client.global.set('mediaName',response.body.name);
 %}

### Add image for Vitamin

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data;boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="media.jpg"
Content-Type: image/jpeg

< VitaminC.jpg

### Add image for Vitamin

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data;boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="media.jpg"
Content-Type: image/jpeg

< Spirulina.jpg

### Get all Vitamins

GET http://localhost:8080/items/getAll

### Get Vitamin by id

GET http://localhost:8080/items/getById?id=2

### Get Vitamin by non-existent id

GET http://localhost:8080/items/getById?id=999

### Create Vitamin without image

POST http://localhost:8080/items/save
Content-Type: application/json

{
  "id": 0,
  "name": "Spirulina",
  "price": 1000,
  "qty": 10
}

### Create Vitamin with image

POST http://localhost:8080/items/save
Content-Type: application/json

{
  "id": 0,
  "name": "Zinc",
  "price": 750,
  "qty": 450,
  "image": "{{mediaName}}"
}

### Remove Vitamin by id

POST http://localhost:8080/items/removeById/13

### Restore Vitamin by id

POST http://localhost:8080/items/restoreById/13

### Get 5 popular Vitamins

GET http://localhost:8080/items/getPopular

