###

POST http://localhost:8080/sales/register
Content-Type: application/json

{
  "itemId": 1,
  "price": 500,
  "qty": 2
}

###

GET http://localhost:8080/sales/getAll

###

GET http://localhost:8080/sales/getById?id=2

###

GET http://localhost:8080/sales/getById?id=999